version: "3.12"
services:
  database:
    container_name: my-postgres
    image: postgres:16.4-debian
    restart: always
    user: postgres
    volumes:
      -pgdata:/var/lib/postgresql/database
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=xxxx
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - 5433:5432
    networks:
      - my-newwork
  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL: admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD: xxx
      - PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
    - 15432:80
    networks:
      - my-newwork
volumes:
  pgdata:
  pgadmin:

networks:
  my-newwork:
